### ISSUE TITLE
Steal content from Raedah repo

### ISSUE THREAD

**Issue by jholdstock** [jholdstock/dcrdevdocs#30]
https://github.com/raedahgroup/dcrdevdocs/blob/master/start.md

**Comment by s-ben** [comment]
Incorporated notes on signatures (PR https://github.com/jholdstock/dcrdevdocs/pull/33)

**Comment by s-ben** [comment]
Now that I've created a page on dcrdocs for [Block Production Times](https://github.com/decred/dcrdocs/pull/995) (which might be a better fit for devdocs?), I don't see any additional content from this to incorporate.

**Comment by jholdstock** [comment]
agreed
